n1 = input('Input Your First Number : ')
n2 = input('Input Your Second Number : ')
n3 = input('Input Your Third Number : ')
n4 = input('Input Your Fourth Number : ')
n5 = input('Input Your Fifth Number : ')
print('Float of %s '%n1+'Equal %s'%float(n1))
print('Complex of %s '%n1+'Equal %s'%complex(n1))
print('Float of %s '%n2+'Equal %s'%float(n2))
print('Complex of %s '%n2+'Equal %s'%complex(n2))
print('Float of %s '%n3+'Equal %s'%float(n3))
print('Complex of %s '%n3+'Equal %s'%complex(n3))
print('Float of %s '%n4+'Equal %s'%float(n4))
print('Complex of %s '%n4+'Equal %s'%complex(n4))
print('Float of %s '%n5+'Equal %s'%float(n5))
print('Complex of %d '%n5+'Equal %d'%complex(n5))